before_script:
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8
  - export LANGUAGE=C.UTF-8
  - export

test:2.0:
  image: ruby:2.0
  script:
    - bundle install && ruby test/detector_test.rb


test:2.1:
  image: ruby:2.1
  script:
    - bundle install && ruby test/detector_test.rb


test:2.2:
  image: ruby:2.2
  script:
    - bundle install && ruby test/detector_test.rb


test:2.3:
  image: ruby:2.3
  script:
    - bundle install && ruby test/detector_test.rb


test:2.4-rc:
  image: ruby:2.4-rc
  script:
    - bundle install && ruby test/detector_test.rb

